name: Deploy LWC

on:
  push:
    paths:
      - 'force-app/main/default/lwc/**'
    branches: 
      - 'Dev-*'

jobs:
    Deploy-To-DevORG:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
          with:
            fetch-depth: 0

        - name: Cache Salesforce CLI
          id: cache-sfdx
          uses: actions/cache@v2
          with:
            path: ~/.local/share/sfdx
            key: sfdx-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
            restore-keys: |
                sfdx-${{ runner.os }}-
        
        - name: Install Salesforce CLI if not cached
          if: steps.cache-sfdx.outputs.cache-hit != 'true'
          run: |
            npm install @salesforce/cli --global

        - name: Login to Salesforce Dev
          run: |
            sfdx org login sfdx-url --set-default --sfdx-url-file <(echo "${{ secrets.SFDX_AUTH_URL_SANDBOX }}") --alias devOrg
        
        - name: Deploy Source Code
          run: |
            sf project deploy start --ignore-conflicts -o devOrg -m LightningComponentBundle